Add EIA ID to Utility
BuildingSync/schema pull request #244
Opened 2020-09-24 14:49 UTC by macintoshpie

## Motivation
It would be nice to have these IDs for identifying utility types.

2020-09-24 14:50 UTC, macintoshpie commented
@corymosiman12 Can you improve the description if needed?

2020-09-24 15:17 UTC, markborkum reviewed
In the linked webpage, the IDs appear to be `xs:nonNegativeInteger`, not `xs:string`, e.g.,

> 3 Phases Energy Services (ID # 21093)

2020-09-24 18:42 UTC, corymosiman12 requested changes

2020-09-24 18:42 UTC, corymosiman12 commented on BuildingSync.xsd
> +          <xs:documentation>ID of the OpenEI EIA Utility.</xs:documentation>
"EIA Utility ID as found in EIA-861 and as available in OpenEI"

2020-09-25 02:41 UTC, corymosiman12 approved these changes

2020-09-25 03:42 UTC, markborkum approved these changes
Changes look good, thanks.

2020-09-25 16:18 UTC, merged