Add PeakType to TimeSeries
BuildingSync/schema pull request #246
Opened 2020-09-24 15:26 UTC by macintoshpie

Also see https://github.com/BuildingSync/TestSuite/issues/35

2020-09-24 15:28 UTC, markborkum approved these changes
Changes look good, thanks.

2020-09-24 18:27 UTC, corymosiman12 requested changes
Minor proposal change

2020-09-24 18:27 UTC, corymosiman12 commented on proposals/2020/Add Peak Type.md
> +This proposal is to add the `auc:PeakType` element in order to specify what type of peak a given reading is.
...`auc:PeakType` element as a child element of the `TimeSeriesType`

2020-09-25 02:48 UTC, corymosiman12 approved these changes

2020-09-25 16:25 UTC, merged