docs: add notes on git naming conventions
BuildingSync/schema pull request #255
Opened 2020-10-07 15:56 UTC by macintoshpie

This creates a doc for developer resources which specifies a format for writing commit messages and branch names.

2020-10-07 16:51 UTC, markborkum requested changes
Please include a "proposal" type.

2020-10-07 17:29 UTC, markborkum approved these changes
Looks good, thanks.

2020-10-07 23:00 UTC, corymosiman12 approved these changes

2020-10-14 14:32 UTC, aviveiros11 approved these changes
lgtm 👍

2020-10-14 14:44 UTC, nllong commented on docs/developer_resources.md
> +- `#1234 feat(schema): add MyElement to ParentElement`
👍

2020-10-14 14:45 UTC, nllong approved these changes
fandidilyastic!

2020-10-14 14:45 UTC, merged