docs(schema): add deprecation policy
BuildingSync/schema pull request #261
Opened 2020-10-21 20:25 UTC by markborkum

2020-10-21 21:54 UTC, macintoshpie approved these changes
Looks great 👍

2020-10-22 02:27 UTC, corymosiman12 commented
Putting it in the schema seems fine but can we also add it to developer docs?

2020-10-22 15:13 UTC, corymosiman12 requested changes
Also add to developer docs

2020-10-22 15:27 UTC, markborkum commented
> Putting it in the schema seems fine but can we also add it to developer docs?

I'd prefer not. If the deprecation policy is an intrinsic part of schema file, then it is exchanged with the schema file and it travels with the schema file, wherever it goes. Having an alternate representation of the deprecation policy in the `docs/` folder is disadvantageous because it would force us to either maintain a duplicate the same content or to maintain a URL, which must be resolvable, within the schema file to a "raw" file (e.g., in the GitHub repository).

2020-10-22 15:30 UTC, corymosiman12 commented
Sure I mean maybe we just make a note in the developer docs that the deprecation policy is defined by the schema doc.  My point is most people look to documentation on Github.  It wouldn't be intuitive to me that the deprecation policy is defined in the Schema itself.

2020-10-28 16:38 UTC, corymosiman12 approved these changes
🌭

2020-11-04 23:48 UTC, nllong approved these changes
looks great.

2020-11-04 23:48 UTC, nllong commented on docs/developer_resources.md
> +Details of the deprecation policy are included in the BuildingSync XML schema file.
👍

2020-11-04 23:51 UTC, merged