Building EQ Example XML
BuildingSync/schema pull request #464
Opened 2023-03-21 22:21 UTC by laurenliz22

Building EQ Example XML

#### Any background context you want to provide?
Adding Building EQ Example

#### What does this PR do?
Adding Building EQ Example

#### How should this be manually tested?
Run Building EQ Example

#### What are the relevant tickets?
N/A

#### Screenshots (if appropriate)

2023-03-22 16:08 UTC, JieXiong9119 approved these changes
Looks good!

2023-03-22 16:39 UTC, kflemin approved these changes

2023-03-27 16:31 UTC, JieXiong9119 requested changes
One minor change required on <auc:UsefulLife>

2023-03-27 17:39 UTC, laurenliz22 commented on examples/BuildingEQ-1.0.0.xml
> +          <auc:UsefulLife>50.0</auc:UsefulLife>
```suggestion
          <auc:UsefulLife>50</auc:UsefulLife>
```

2023-03-28 16:17 UTC, JieXiong9119 approved these changes
Nice! And we will need to change this accordingly in the use case and the website repos

2023-03-28 16:18 UTC, merged