Add AuditCycles
BuildingSync/schema pull request #478
Opened 2023-06-12 21:55 UTC by JieXiong9119

#### Any background context you want to provide?
FEMP CERL use case

#### What does this PR do?
See proposal

#### How should this be manually tested?

#### What are the relevant tickets?
#466 

#### Screenshots (if appropriate)

2023-06-13 15:07 UTC, markborkum commented
@JieXiong9119, Could we add more metadata elements to the new `auc:AuditCycle` element, e.g., the audit cycle name, the reporting juristdiction, etc. (or, dare I suggest it, an `auc:UserDefinedFields` child element)?

2023-06-14 16:43 UTC, markborkum commented
> Is it possible to map the cycle name to its ID?

In Audit Template, yes. A database constraint ensures that audit cycle names are unique (within the scope of a given reporting jurisdiction). At import, the tool would find the `//auc:Report/auc:UserDefinedFields/auc:UserDefinedField[auc:FieldName = 'Audit Template Report Type']/auc:FieldValue` element and resolve the corresponding reporting jurisdiction. Then, it is straightforward to resolve the audit cycle by its name.

> Is a Note field good for reporting jurisdiction?

This is a question for CERL. Currently, the report type and audit cycle name are sufficient to identify the reporting jurisdiction and audit cycle, respectively. If additional metadata are requested by CERL, it could be exported from Audit Template using the `auc:UserDefinedFields` element.

2023-06-14 20:12 UTC, JieXiong9119 commented
@markborkum Check this update out!

2023-06-20 16:51 UTC, markborkum requested changes
Could the new `auc:AuditCycles` element be a child of the `auc:Facility` element (instead of the `auc:Report` element)?

This way, the same audit cycle could be referenced by multiple reports in the same XML document, e.g., using a new `auc:LinkedAuditCycle` element:

```xml
<auc:Facility ID="facility1">
  <!-- ... -->
  <auc:AuditCycles>
    <auc:AuditCycle ID="cycle1">
      <auc:AuditCycleName>Example Audit Cycle</auc:AuditCycleName>
      <auc:AuditCycleStartYear>2023</auc:AuditCycleStartYear>
      <auc:AuditCycleEndYear>2025</auc:AuditCycleEndYear>
    </auc:AuditCycle>
  </auc:AuditCycles>
  <!-- ... -->
  <auc:Reports>
    <auc:Report ID="report1">
      <!-- ... -->
      <auc:LinkedAuditCycle IDref="cycle1">
        <auc:YearOfAuditCycle>1</auc:YearOfAuditCycle>
      </auc:LinkedAuditCycle>
      <!-- ... -->
    </auc:Report>
  </auc:Reports>
  <!-- ... -->
</auc:Facility>
```

2023-06-20 16:51 UTC, markborkum commented on proposals/2023/Add AuditCycles.md
> +      </xs:element >
Please delete trailing whitespace after "element".

2023-06-22 17:21 UTC, JieXiong9119 commented
> Could the new `auc:AuditCycles` element be a child of the `auc:Facility` element (instead of the `auc:Report` element)?
> 
> This way, the same audit cycle could be referenced by multiple reports in the same XML document, e.g., using a new `auc:LinkedAuditCycle` element:
> 
> ```
> <auc:Facility ID="facility1">
>   <!-- ... -->
>   <auc:AuditCycles>
>     <auc:AuditCycle ID="cycle1">
>       <auc:AuditCycleName>Example Audit Cycle</auc:AuditCycleName>
>       <auc:AuditCycleStartYear>2023</auc:AuditCycleStartYear>
>       <auc:AuditCycleEndYear>2025</auc:AuditCycleEndYear>
>     </auc:AuditCycle>
>   </auc:AuditCycles>
>   <!-- ... -->
>   <auc:Reports>
>     <auc:Report ID="report1">
>       <!-- ... -->
>       <auc:LinkedAuditCycle IDref="cycle1">
>         <auc:YearOfAuditCycle>1</auc:YearOfAuditCycle>
>       </auc:LinkedAuditCycle>
>       <!-- ... -->
>     </auc:Report>
>   </auc:Reports>
>   <!-- ... -->
> </auc:Facility>
> ```

That's a good idea, but Iwould prefer to put it under `auc:site` (and probably `auc:Building` as well) instead of `auc:Facility`. How do you think of that?

2023-06-22 17:51 UTC, markborkum commented
@JieXiong9119, Being a child element of `auc:Facility` is preferred because it would align with the implementation for other top-level concepts that are referenced at lower levels in the XML tree. Other child elements of `auc:Facility` include: `auc:Systems`, `auc:Schedules`, `auc:Measures`, and `auc:Contacts`.

2023-06-22 19:28 UTC, JieXiong9119 commented
> @JieXiong9119, Being a child element of `auc:Facility` is preferred because it would align with the implementation for other top-level concepts that are referenced at lower levels in the XML tree. Other child elements of `auc:Facility` include: `auc:Systems`, `auc:Schedules`, `auc:Measures`, and `auc:Contacts`.

Make sense. I'll modify and update soon.

2023-06-22 21:09 UTC, JieXiong9119 commented
@markborkum Check the updates! 
I enable multiple `AuditCycle`s to be referred via `auc:LinkedAuditCycles\auc:LinkedAuditCycle`.

2023-06-23 14:40 UTC, markborkum commented
@JieXiong9119, The latest changes look good, thanks.

Can we work on the `xs:documentation` elements next, please? The flavor text should align with that of other, preexisting XML elements in the schema.

- **AuditCycleType** - We need to define the term "audit cycle". For some organizations, such as CERL or FEMP, it refers to a period of time in which multiple audits may be conducted; whereas, for others, it refers to the multi-step process of actually conducting a single audit.
- **AuditCycleName** - Looking at a similarly named element, like `auc:PremisesName`, this should be something like "Name identifying the audit cycle."
- **AuditCycleNotes** - Looking at `auc:PremisesNotes`, this should be something like "Details about the audit cycle."
- **AuditCycleStartYear** - Looking at `auc:AssessmentYear`, this should be something like "Year the audit cycle starts, inclusive. (CCYY)"
- **AuditCycleEndYear** - Looking at `auc:AssessmentYear`, this should be something like "Year the audit cycle ends, inclusive. (CCYY)"
- **LinkedAuditCycle** - Looking at `auc:LinkedHeatingPlantID`, this should be something like "ID number of AuditCycle for this report."
- **YearOfAuditCycle** - Looking at `auc:YearOfManufacture`, the "Year" and "YearOf" prefixes indicate that the content of the element is a `xs:gYear` literal. We should consider redefining the content of this element to be a `xs:gYear` (for consistency) or renaming this element to indicate that the content is a positive integer, e.g., `IndexedYearOfAuditCycle`.

2023-06-24 00:00 UTC, JieXiong9119 commented
@markborkum Description updated!

2023-06-29 19:46 UTC, JieXiong9119 commented
Hey @markborkum , would you be able to review it before our deadline of BuildingSync 6/30 milestone tomorrow?

2023-06-29 20:09 UTC, markborkum commented
@JieXiong9119, 

> For some organizations, such as CERL or FEMP, it refers to a period of time in which multiple audits may be conducted; whereas, for others, it refers to the multi-step process of actually conducting a single audit.

I didn't intend for that text to be used verbatim. I meant that we need to choose one definition (most likely, the "period of time" definition, but we would need to confirm this with CERL and/or FEMP).

2023-06-30 14:33 UTC, markborkum commented
@JieXiong9119, To align with the documentation for other elements, can we change the definition for the `AuditCycle` element to: _"A period of time in which multiple audits may be conducted."_

Also, please update the proposal so that the examples match the renamed XML elements (e.g., replace `YearOfAuditCycle` with `IndexYearOfAuditCycle`).

2023-06-30 16:28 UTC, JieXiong9119 commented
@markborkum Check out the update!

2023-06-30 16:32 UTC, markborkum commented
@JieXiong9119, According to GitHub, the last commit, 755fa64554aeb31478c5f62aeb0ad5c03f21a4f7, was yesterday.

2023-06-30 16:58 UTC, markborkum approved these changes
Changes look good. Thanks, @JieXiong9119!

2023-06-30 17:01 UTC, merged