Make migrations scripts
BuildingSync/schema pull request #483
Opened 2023-08-28 20:04 UTC by haneslinger

Cute little script to modified BuildingSync files from 2.4 to 2.5

2023-08-28 20:37 UTC, ThibaultMarzullo requested changes
This looks good, thank you! On top of the comments that I made throughout the files, can you also include one file for testing? If we do not have an example XML with the right fields, maybe you can amend a minimalist XML like [this L000 pre-simulation XML](https://github.com/BuildingSync/use-cases/blob/main/BuildingSync-Gem/examples/L000_Pre-Simulation-1.0.0_01.xml).

2023-08-28 20:37 UTC, ThibaultMarzullo commented on migration_scripts/README.md
Can you add an example of usage please?

2023-08-28 20:37 UTC, ThibaultMarzullo commented on migration_scripts/upgrade_from_2.4_to_2.5.py
Looks good!

2023-08-28 20:37 UTC, ThibaultMarzullo commented on migration_scripts/upgrade_from_2.4_to_2.5.py
> +        usefulLife.text = usefulLife.text.split(".", 1)[0]
```suggestion
        usefulLife.text = str(int(usefulLife.text))
```
Currently, we only round down, is this right? If so, would this also round up when necessary?

2023-08-28 20:37 UTC, ThibaultMarzullo commented on migration_scripts/upgrade_from_2.4_to_2.5.py
> +    tree.write(file_path)
Can you save the original file under a different name like `ye_olde_excemelle` or a sober and more appropriate suffix like `my_xml_old`?

2023-08-28 22:45 UTC, haneslinger commented
> This looks good, thank you! On top of the comments that I made throughout the files, can you also include one file for testing? If we do not have an example XML with the right fields, maybe you can amend a minimalist XML like [this L000 pre-simulation XML](https://github.com/BuildingSync/use-cases/blob/main/BuildingSync-Gem/examples/L000_Pre-Simulation-1.0.0_01.xml).

There are mutliple v2.4 files in the repo currently, for example, `docs/notebooks/bsync_examples/example-smalloffice-level2.xml` (UsefulLife on L1408). Are you looking for something more specific?

2023-08-28 22:55 UTC, JieXiong9119 commented
This one looks good, but I want to point out that we had something built for version converting by using xsl in [here](https://github.com/BuildingSync/schema/tree/develop-v3/translation). I'm not sure if xsl is something more generic for xml conversion and might be useful for future development.

2023-08-28 23:02 UTC, haneslinger commented
oh, this would have been great to know about. I haven't worked with xsl, let me dig into it.

2023-08-28 23:10 UTC, haneslinger commented
wait, these scripts are for v2 to v3, what happened to v3?

2023-08-28 23:16 UTC, JieXiong9119 commented
> wait, these scripts are for v2 to v3, what happened to v3?

v3 is a frozen version that was determined not to be released in the near future. I don't think you want to dig into xslt - I suggest we go with pure Python but refer to that v3 xslt tool for the extensibility of this script (e.g. adding a comment note like the one in v3 converter such as "This BuildingSync v2.5 document was generated from a BuildingSync v2.4 document via ....").

2023-08-29 15:20 UTC, ThibaultMarzullo approved these changes
This is looking good, thanks Hannah!
I like Jie's suggestion of adding a comment saying that an XML was converted from 2.4 to 2.5 with this script.

2023-08-29 16:29 UTC, haneslinger commented
I want to be clear: You want a comment in the generated/updated xml file stating it was modified by the script?

2023-08-29 16:50 UTC, JieXiong9119 commented
> I want to be clear: You want a comment in the generated/updated xml file stating it was modified by the script?

Yes. Something like [this line](https://github.com/BuildingSync/schema/blob/7edc2f9a5a57041ffa164b16be398d9f0917346c/translation/v2_to_v3.xsl#L21C22-L21C22) in the xslt tool for v2-to-v3, which adds a comment on top of the generated xml.

2023-08-30 20:46 UTC, JieXiong9119 approved these changes
Looks good. Thank you Hannah!

2023-08-30 20:51 UTC, merged