Update examples to 2.5
BuildingSync/schema pull request #487
Opened 2023-09-28 19:54 UTC by JieXiong9119

Update examples to 2.5 as it's released

2023-09-28 20:28 UTC, markborkum approved these changes
Changes look good. Thanks, @JieXiong9119.

2023-09-29 19:05 UTC, ThibaultMarzullo requested changes
Looks good, thanks @JieXiong9119.
One remaining item is updating [the DOE Reference Primary School L100 and L200 Python notebook](https://github.com/BuildingSync/schema/blob/develop-v2/docs/notebooks/bsync_examples/Primary-School-Levels1-2.md) and we're good to go.

2023-09-29 19:27 UTC, JieXiong9119 commented
> Looks good, thanks @JieXiong9119. One remaining item is updating [the DOE Reference Primary School L100 and L200 Python notebook](https://github.com/BuildingSync/schema/blob/develop-v2/docs/notebooks/bsync_examples/Primary-School-Levels1-2.md) and we're good to go.

Updated. check it out!

2023-09-29 22:07 UTC, ThibaultMarzullo approved these changes

2023-09-29 22:21 UTC, merged